name:
  linklater
version:
  4.0.0.0
author:
  Hao Lian <hi@haolian.org>
synopsis:
  A Haskell library for the Slack API
homepage:
  https://github.com/hlian/linklater
bug-reports:
  https://github.com/hlian/linklater/issues
license:
  BSD3
license-file:
  LICENSE
category:
  Network
description: |
  <https://github.com/hlian/linklater/blob/master/README.md ~please see our lovely README.md~>
dependencies:
  - aeson
  - base
  - base-prelude
  - bytestring
  - containers
  - exceptions
  - http-types
  - lens
  - lens-aeson
  - mtl
  - tasty
  - tasty-hunit
  - text
  - uri-bytestring
  - wai
  - wreq
library:
  source-dirs: lib/
tests:
  linklater-tests:
    main: Main.hs
    source-dirs: test/
    dependencies: linklater
